import { NPC_SHIPS } from "./ships";
import type { PluginListing } from "./types";

export const CATALOG: PluginListing[] = [
  {
    id: "omaplug",
    name: "Plugin Manager",
    version: "1.4.0",
    author: "Fross",
    origin: NPC_SHIPS.fross,
    description:
      "Manage installed Omarchy plugins from the bar: enable, disable, update, install from git, and remove third-party checkouts.",
    git: "https://github.com/fross100/omaplug.git",
    kinds: ["bar-widget", "panel"],
    tags: ["manager", "bar", "updates"],
    category: "tools",
    license: "MIT",
  },
  {
    id: "b.okomart",
    name: "Okomart",
    version: "1.2.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description:
      "Storefront and manager for Omarchy plugins. Search, preview, install, enable, disable, update, and remove without the terminal.",
    git: "https://github.com/brianblakely/omarchy-plugins.git",
    kinds: ["overlay", "panel"],
    tags: ["storefront", "manager"],
    category: "tools",
    license: "MIT",
  },
  {
    id: "robzolkos.github",
    name: "Omarchy GitHub",
    version: "1.1.0",
    author: "Rob Zolkos",
    origin: NPC_SHIPS.zolkos,
    description:
      "Keyboard-first GitHub command center in the bar — reviews, notifications, and the work that needs you, without another browser tab.",
    git: "https://github.com/robzolkos/omarchy-github.git",
    kinds: ["bar-widget", "panel", "service"],
    tags: ["github", "dev", "bar"],
    category: "dev",
    license: "MIT",
  },
  {
    id: "io.github.luccast.omarr",
    name: "omARR",
    version: "1.0.2",
    author: "luccast",
    origin: NPC_SHIPS.luccast,
    description:
      "Arr-stack homelab plugin for the bar: live Sonarr, Radarr, SABnzbd, Plex, Jellyfin, and qBittorrent with queue controls.",
    git: "https://github.com/luccast/omARR.git",
    kinds: ["bar-widget", "panel"],
    tags: ["homelab", "arr", "sonarr"],
    category: "homelab",
    license: "MIT",
  },
  {
    id: "io.github.mtolhuys.news-radar",
    name: "News Radar",
    version: "0.2.1",
    author: "mtolhuys",
    origin: NPC_SHIPS.mtolhuys,
    description:
      "A keyboard-first front page for meaningful Omarchy activity — launcher and bar surfaces for community signal.",
    git: "https://github.com/mtolhuys/omarchy-news-radar.git",
    kinds: ["bar-widget", "overlay"],
    tags: ["news", "launcher", "community"],
    category: "news",
    license: "MIT",
  },
  {
    id: "io.github.rmcfarlin.theme-studio",
    name: "Theme Studio",
    version: "1.0.0",
    author: "rmcfarlin",
    origin: NPC_SHIPS.rmcfarlin,
    description:
      "Compose and preview Omarchy themes from the shell. Edit palettes, try a look, and write it back without leaving the session.",
    git: "https://github.com/rmcfarlin/omarchy-theme-studio.git",
    kinds: ["overlay"],
    tags: ["theme", "color", "editor"],
    category: "theme",
    license: "MIT",
  },
  {
    id: "quickshell.spotify",
    name: "Omarchy Spotify",
    version: "1.0.3",
    author: "stappmus",
    origin: NPC_SHIPS.stappmus,
    description:
      "Spotify in Quickshell, not Chromium — about 60 MB versus ~950 MB for the desktop client, with theming, a mini player, and lyrics.",
    git: "https://github.com/stappmus/Omarchy-Spotify.git",
    kinds: ["bar-widget", "panel", "service"],
    tags: ["spotify", "music", "media"],
    category: "media",
    license: "MIT",
  },
  {
    id: "io.github.howdyitskyle.weathering",
    name: "Weathering",
    version: "1.3.0",
    author: "howdyitskyle",
    origin: NPC_SHIPS.kyle,
    description:
      "One weather pill, one panel: current conditions, metrics, hourly strip, 7-day forecast, air quality, and sun times. Open-Meteo, no API key.",
    git: "https://github.com/howdyitskyle/weathering-omarchy-plugin.git",
    kinds: ["bar-widget", "panel"],
    tags: ["weather", "forecast", "bar"],
    category: "weather",
    license: "MIT",
  },
  {
    id: "io.github.calebhat.weather",
    name: "Detailed Weather",
    version: "1.1.0",
    author: "calebhat",
    origin: NPC_SHIPS.caleb,
    description:
      "A bar pill that replaces omarchy.weather: remaining-hour forecast, ten-day outlook, and a radar jump. Same location file Omarchy already uses.",
    git: "https://github.com/calebhat/omarchy-weather.git",
    kinds: ["bar-widget", "panel"],
    tags: ["weather", "radar"],
    category: "weather",
    license: "MIT",
  },
  {
    id: "rasmus.fmi-weather",
    name: "FMI Weather",
    version: "1.0.0",
    author: "rejhaa",
    origin: NPC_SHIPS.rejhaa,
    description:
      "Stock weather widget, national institutes instead of wttr.in. FMI HARMONIE across northern Europe, MET Norway everywhere else.",
    git: "https://github.com/rejhaa/omarchy-plugin-fmi-weather.git",
    kinds: ["bar-widget"],
    tags: ["weather", "fmi", "nordic"],
    category: "weather",
    license: "MIT",
  },
  {
    id: "b.blink",
    name: "Blink",
    version: "1.0.1",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description:
      "Briefly flashes a border over the active Hyprland window so you can find focus after a workspace jump.",
    git: "https://github.com/brianblakely/blink.git",
    kinds: ["service"],
    tags: ["hyprland", "focus", "desktop"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "b.omacal",
    name: "Omacal",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Omarchy-native day and time label with a mini calendar popup. Click the clock, see the month.",
    git: "https://github.com/brianblakely/omacal.git",
    kinds: ["bar-widget", "panel"],
    tags: ["calendar", "clock"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "b.omadoro",
    name: "Omadoro",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "A Pomodoro timer for the Omarchy bar. Work, rest, and a quiet count.",
    git: "https://github.com/brianblakely/omadoro.git",
    kinds: ["bar-widget", "panel"],
    tags: ["pomodoro", "timer", "focus"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "b.omanote",
    name: "Omanote",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Scratch notes that live next to the bar. Capture, keep, dismiss.",
    git: "https://github.com/brianblakely/omanote.git",
    kinds: ["panel", "overlay"],
    tags: ["notes", "scratch"],
    category: "tools",
    license: "MIT",
  },
  {
    id: "b.peek",
    name: "Peek",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Quick-look overlay for files and images without opening a full viewer.",
    git: "https://github.com/brianblakely/peek.git",
    kinds: ["overlay"],
    tags: ["files", "preview"],
    category: "tools",
    license: "MIT",
  },
  {
    id: "b.omasnap",
    name: "Omasnap",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Screenshot overlay tuned for Omarchy: grab, annotate, drop onto the clipboard.",
    git: "https://github.com/brianblakely/omasnap.git",
    kinds: ["overlay"],
    tags: ["screenshot", "clipboard"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "b.omastonk",
    name: "Omastonk",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Markets pulse in the bar. A small stonk ticker that stays out of the way.",
    git: "https://github.com/brianblakely/omastonk.git",
    kinds: ["bar-widget", "panel"],
    tags: ["finance", "ticker"],
    category: "status",
    license: "MIT",
  },
  {
    id: "b.omanews",
    name: "Omanews",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Headline panel for a handful of feeds. Keyboard through the day's stories.",
    git: "https://github.com/brianblakely/omanews.git",
    kinds: ["panel", "bar-widget"],
    tags: ["rss", "news"],
    category: "news",
    license: "MIT",
  },
  {
    id: "b.omahud",
    name: "Omahud",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "A denser system HUD: load, memory, and the few gauges you actually glance at.",
    git: "https://github.com/brianblakely/omahud.git",
    kinds: ["bar-widget", "panel"],
    tags: ["hud", "system"],
    category: "status",
    license: "MIT",
  },
  {
    id: "b.omaled",
    name: "Omaled",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Tiny LED-style status dots for services you care about, parked on the bar.",
    git: "https://github.com/brianblakely/omaled.git",
    kinds: ["bar-widget"],
    tags: ["status", "services"],
    category: "status",
    license: "MIT",
  },
  {
    id: "mwikala.world-time",
    name: "World Time",
    version: "1.0.0",
    author: "mwikala",
    origin: NPC_SHIPS.mwikala,
    description: "Multiple timezones in the bar. Traveling, remote crews, one glance.",
    git: "https://github.com/mwikala/omarchy-world-time.git",
    kinds: ["bar-widget", "panel"],
    tags: ["time", "timezone"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "yuters.flight-radar",
    name: "Flight Radar",
    version: "1.0.0",
    author: "yuters",
    origin: NPC_SHIPS.yuters,
    description: "Nearby aircraft in a summoned panel. Watch the sky from the shell.",
    git: "https://github.com/yuters/omarchy-flight-radar.git",
    kinds: ["panel", "overlay"],
    tags: ["ads-b", "map", "flights"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "kristoffer.expose",
    name: "Exposé",
    version: "1.0.0",
    author: "kristofferR",
    origin: NPC_SHIPS.kristoffer,
    description: "Window overview for Hyprland, Omarchy-native. Spread, pick, focus.",
    git: "https://github.com/kristofferR/omarchy-expose.git",
    kinds: ["overlay"],
    tags: ["windows", "overview", "hyprland"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "ahmed.keysmith",
    name: "Keysmith",
    version: "1.0.0",
    author: "Ahmed-Sinkeat",
    origin: NPC_SHIPS.ahmed,
    description: "Add, change, and remove Omarchy shortcuts without editing config files by hand.",
    git: "https://github.com/Ahmed-Sinkeat/keysmith.git",
    kinds: ["overlay", "panel"],
    tags: ["keybinds", "config"],
    category: "tools",
    license: "MIT",
  },
  {
    id: "ivan.hive",
    name: "Hive Status",
    version: "1.0.0",
    author: "Ivan Kuznetsov",
    origin: NPC_SHIPS.ivan,
    description: "Monitor Hive instances and active tasks from the Omarchy bar.",
    git: "https://github.com/ivankuznetsov/hive-omarchy.git",
    kinds: ["bar-widget", "panel"],
    tags: ["hive", "tasks", "ai"],
    category: "dev",
    license: "MIT",
  },
  {
    id: "godhiraj.omaudit",
    name: "Omaudit Status",
    version: "1.0.0",
    author: "godhiraj",
    origin: NPC_SHIPS.godhiraj,
    description: "Audit and update posture for the machine, surfaced as a bar widget.",
    git: "https://github.com/godhiraj-code/omarchy-omaudit-status.git",
    kinds: ["bar-widget"],
    tags: ["audit", "updates", "security"],
    category: "status",
    license: "MIT",
  },
  {
    id: "cause.omaloom",
    name: "Omaloom",
    version: "1.0.0",
    author: "Cause-of-a-Kind",
    origin: NPC_SHIPS.cause,
    description: "A loom-inspired workspace switcher overlay. Threads of work, one summon.",
    git: "https://github.com/Cause-of-a-Kind/omaloom.git",
    kinds: ["overlay", "menu"],
    tags: ["workspaces", "switcher"],
    category: "desktop",
    license: "MIT",
  },
  {
    id: "keith.omanetwatch",
    name: "Omanetwatch",
    version: "1.0.0",
    author: "keithnyc",
    origin: NPC_SHIPS.keith,
    description: "Watch interfaces, routes, and a few hosts from the bar. Network, quietly.",
    git: "https://github.com/keithnyc/omanetwatch.git",
    kinds: ["bar-widget", "panel"],
    tags: ["network", "watch"],
    category: "status",
    license: "MIT",
  },
  {
    id: "b.codex-notifications",
    name: "Codex Notifications",
    version: "1.0.0",
    author: "Brian Blakely",
    origin: NPC_SHIPS.blakely,
    description: "Route Codex / agent notifications into the Omarchy notification stream.",
    git: "https://github.com/brianblakely/omarchy-codex-notifications.git",
    kinds: ["service"],
    tags: ["agents", "notifications"],
    category: "dev",
    license: "MIT",
  },
  {
    id: "nightdevil.bt-codecs",
    name: "BT Codecs",
    version: "1.0.0",
    author: "nightdevil00",
    origin: NPC_SHIPS.luccast,
    description:
      "Bluetooth codec readout for the bar so you know whether the headphones actually negotiated LDAC.",
    git: "https://github.com/nightdevil00/bt.codecs.git",
    kinds: ["bar-widget"],
    tags: ["bluetooth", "audio"],
    category: "status",
    license: "MIT",
  },
];

export const CATALOG_BY_ID = Object.fromEntries(CATALOG.map((p) => [p.id, p]));
